server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration: ## 클라이언트 설정
          keycloak1:
            clientId: oauth2-client-app
            clientSecret: Bi7RyJ72QB2BNKWS51RC7LhoNDFSLkFQ
            authorizationGrantType: authorization_code
            scope: openid,profile
            clientAuthenticationMethod: client_secret_basic
            redirectUri: http://localhost:8081/login/oauth2/code/keycloak
            provider: keycloak

          keycloakWithPKCE:
            clientId: oauth2-client-app2
            clientSecret: amHsOErSoYR4dZkh3eYQvOzpMc6ynROP
            authorizationGrantType: authorization_code
            scope: openid,profile
            clientAuthenticationMethod: client_secret_post
            redirectUri: http://localhost:8081/login/oauth2/code/keycloak
            provider: keycloak

          keycloak2:
            clientId: oauth2-client-app3
            authorizationGrantType: implicit
            scope: openid,profile
            clientAuthenticationMethod: none
            redirectUri: http://localhost:8081/home
            provider: keycloak

        provider:
          keycloak:
            issuerUri: http://localhost:8080/realms/oauth2
            authorizationUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            jwkSetUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            tokenUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            userInfoUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            userNameAttribute: preferred_username
#          keycloak:
#            authorization-grant-type: authorization_code
#            client-id: oauth2-client-app
#            client-name: oauth2-client-app
#            client-secret: Bi7RyJ72QB2BNKWS51RC7LhoNDFSLkFQ
#            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
#            clientAuthenticationMethod: client_secret_post
#            scope: email, profile
#
#        provider:
#          keycloak:
#            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
#            issuer-uri: http://localhost:8080/realms/oauth2
#            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
#            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
#            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username

